apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cronner
  description: This is a cronner - modified 2
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: [team-A, team-b@lastpass.com]
  lifecycle: experimental
